apiVersion: v1
kind: Pod
metadata:
 name: first-deployment
 labels:
  app: webapp
spec:
#   selector:
#    matchLabels:
#      app: webapp
#   replicas: 2
#   template:
#    metadata:
#     name: webapp-pod
#     labels:
#      app: webapp
#    spec:
  containers:
   - name: webapp
     image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: webapp
  ports:
   - name: http
     port: 80
     nodePort: 30020
  type: NodePort
